### ISSUE TITLE
boilerplate is not consistent / missing.

### ISSUE THREAD

**Issue by purnendudash** [liliapro/moodle-local_wsmanager#1]
All plugin file should have some common explicit GPL license statement. Kindly check and include the same.

For more information on this see:
https://moodledev.io/general/community/plugincontribution/checklist#boilerplate

https://github.com/liliapro/moodle-local_wsmanager/blob/726afc2c04a5918c22ce423325b00f6d64abea4a/webservices.php#L22

**Comment by liliapro** [comment]
Hi @purnendudash ! This small fix done at new version

https://github.com/liliapro/moodle-local_wsmanager/blob/eb19dfede7eda99d9284f726bf3f9a08da6e821e/webservices.php#L20
