### ISSUE TITLE
Incorrect Camel case used

### ISSUE THREAD

**Issue by purnendudash** [liliapro/moodle-local_wsmanager#2]
https://github.com/liliapro/moodle-local_wsmanager/blob/726afc2c04a5918c22ce423325b00f6d64abea4a/lang/en/local_wsmanager.php#L39

Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by liliapro** [comment]
Thanks @purnendudash i got it

https://github.com/liliapro/moodle-local_wsmanager/blob/eb19dfede7eda99d9284f726bf3f9a08da6e821e/lang/en/local_wsmanager.php#L36
