### ISSUE TITLE
sesskey not always checked & direct usage of parameters without the clean

### ISSUE THREAD

**Issue by purnendudash** [liliapro/moodle-local_wsmanager#4]
https://github.com/liliapro/moodle-local_wsmanager/blob/726afc2c04a5918c22ce423325b00f6d64abea4a/locallib.php#L1289

Tokens and other parameters were directly passed via js side.

And while doing write operation I cant see any sesskey check not any clean and sanitisation was done.

Could you please recheck / explain the same.

**Comment by liliapro** [comment]
Wow @purnendudash you are absolutely right! It's amazing that you got it, **thanks**!

https://github.com/liliapro/moodle-local_wsmanager/blob/eb19dfede7eda99d9284f726bf3f9a08da6e821e/classes/output/webservices.php#L252
